# Generated by Django 4.0.2 on 2022-02-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('horario_func', models.CharField(max_length=5, verbose_name='horário de funcionamento')),
                ('idade_minima', models.IntegerField(verbose_name='idade mínima')),
            ],
            options={
                'verbose_name': 'atração',
                'verbose_name_plural': 'atrações',
            },
        ),
    ]
