# Generated by Django 4.0.2 on 2022-02-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atracao',
            name='horario_func',
            field=models.CharField(max_length=25, verbose_name='horário de funcionamento'),
        ),
    ]
